### ISSUE TITLE
Feature-request: make browserify consume inlined sourcemaps

### ISSUE THREAD

**Issue by dy** [L8D/sourceify#1]
Basically to make https://github.com/browserify/browserify/issues/772 work

**Comment by L8D** [comment]
I believe this is a transform that solves this exact problem? Is this a bug report because it only supports a specific type of source map comment syntax?

**Comment by jeremija** [comment]
In my case I have a few TypeScript projects in a hoisted Lerna monorepo.

The folder structure is like this:

```
lerna.json
package.json
node_modules/
   @jeremija/
      common -> ../../packages/common
      client -> ../../packages/client
packages/
   tsconfig.common.json
   common/
      lib/
      src/
      package.json
      tsconfig.json
   client/
      lib/
      src/
      package.json
      tsconfig.json
   client-impl-1/
      lib/
      src/
      package.json
      tsconfig.json
   client-impl-2/
      lib/
      src/
      package.json
      tsconfig.json
```

I tried compiling `client-impl-1` with the following arguments:

```
watchify src/index.ts \
  -p [ tsify --project .] \ 
  -t [ sourceify ] \
  -g [ loose-envify purge --NODE_ENV development ] \
  -v --debug -o build/client.js
```

But no source-maps are used for `@jeremija/client` and `@jeremija/common`. Am I doing something wrong here?

I added a logging statement to the main exported function of `sourceify` to see which files are processed, and it only lists files from the project I'm compiling (`client-impl-1`).

**EDIT** It seems to be working when using the `-g` (global transform) command instead of `-t`. I can see that the source has changed and now contains the base64-encoded embedded source map. However, the browsers (tried on Firefox and Chrome) don't seem to load that source map. I this is because browserify creates it's own source map for the bundle, and the aforementioned embedded `//# sourceMappingUrl` comments are ignored.

**Comment by jeremija** [comment]
@dy I just submitted a pull request that should fix this issue - could you check if this fixes this issue for you (`npm install https://github.com/jeremija/sourceify#sources-content`) ? And try to use the global transform: `-g [ sourceify ]`. Thanks!
